### ISSUE TITLE
Will not compile on 4.15

### ISSUE THREAD

**Issue by mikebetz42** [ceton/infinitv_pcie#11]
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-68-generic'
  CC [M]  /home/myth-dvr/Downloads/ceton/ctn91xx_net.o
/home/myth-dvr/Downloads/ceton/ctn91xx_net.c: In function ‘ctn91xx_net_rx_skb’:
/home/myth-dvr/Downloads/ceton/ctn91xx_net.c:323:11: error: ‘struct net_device’ has no member named ‘last_rx’
     netdev->last_rx = jiffies;
           ^~
/home/myth-dvr/Downloads/ceton/ctn91xx_net.c: In function ‘ctn91xx_net_isr_ex’:
/home/myth-dvr/Downloads/ceton/ctn91xx_net.c:377:23: error: ‘struct net_device’ has no member named ‘last_rx’
                 netdev->last_rx = jiffies;
                       ^~
scripts/Makefile.build:330: recipe for target '/home/myth-dvr/Downloads/ceton/ctn91xx_net.o' failed
make[2]: *** [/home/myth-dvr/Downloads/ceton/ctn91xx_net.o] Error 1
Makefile:1577: recipe for target '_module_/home/myth-dvr/Downloads/ceton' failed
make[1]: *** [_module_/home/myth-dvr/Downloads/ceton] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-68-generic'
Makefile:38: recipe for target 'ctn91xx_module' failed
make: *** [ctn91xx_module] Error 2
myth-dvr@myth-dvr:~/Downloads/ceton$ sudo nano ctn91xx_net.c

**Comment by JamesRHarris** [comment]
This was already fixed a while ago. you need to update your source. see https://github.com/ceton/infinitv_pcie/commit/f0f953f5c1ce8b07ee3a680c247f2da8aa6de589

**Comment by mikebetz42** [comment]
Updated and fixed.... sorry, thought I had updated already.
